api:
  host: "0.0.0.0"
  port: 8000
  debug: false

database:
  type: "dynamodb"
  dynamodb:
    table_name: "fiis_test"
    region: "us-east-1"
    endpoint: "http://localhost:8002"  # Local DynamoDB for integration tests
    access_key: "dummy"
    secret_key: "dummy"

external:
  status_invest:
    base_url: "https://statusinvest.com.br/fundos-imobiliarios/"
    timeout: 30

scheduler:
  scrape_interval_hours: 8
